sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xvfb
    - gcc-4.8
    - g++-4.8
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CXX=g++-4.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
