environment:
  nodejs_version: "7"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn install
version: 1.0.{build}
skip_non_tags: true
build_script:
- cmd: npm run release
test: off
