environment:
  nodejs_version: "8"
# - ps: Set-ScreenResolution 1920 1080
os: unstable
platform:
  - x64
cache:
- node_modules -> package.json
- app/node_modules -> app/package.json
- "%LOCALAPPDATA%\\Yarn"
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - yarn install
version: 1.0.{build}
skip_non_tags: true
build_script:
- cmd: npm run dist
